[book]
authors = ["arHSM"]
language = "en"
multilingual = false
src = "src"
title = "Unofficial Discord Documentation"
description = "Unofficial Discord Documentation - Documenting the undocumented side of the Discord API"

[output.html]
default-theme = "dark"
preferred-dark-theme = "dark"
curly-quotes = true
copy-fonts = false
no-section-label = true
git-repository-url = "https://github.com/discord-undoc/discord-undoc.github.io"
git-repository-icon = "source"
edit-url-template = "https://github.com/discord-undoc/discord-undoc.github.io/edit/master/{path}"

[output.html.print]
enable = false

[output.html.playground]
copyable = false
copy-js = false

[output.html.redirect]
"/server.html" = "https://discord.gg/zVB5P96GE2"
"/github.html" = "https://github.com/discord-undoc"
"/github/theme.html" = "https://github.com/discord-undoc/discord-undoc-theme"
"/github/types.html" = "https://github.com/discord-undoc/discord-undoc-types"
