[book]
authors = ["arHSM"]
language = "en"
multilingual = false
src = "src"
title = "Unofficial Discord Documentation"
description = "Unofficial Discsord Documentation - Documenting the undocumented side of the Discord API"

[preprocessor.discord-undoc]
command = "python ./theme/discord_undoc.py"

[output.html]
default-theme = "dark"
preferred-dark-theme = "dark"
curly-quotes = true
copy-fonts = false
git-repository-url = "https://github.com/discord-undoc/discord-undoc.github.io"
git-repository-icon = "source"
edit-url-template = "https://github.com/discord-undoc/discord-undoc.github.io/edit/master/{path}"

[output.html.print]
enable = false

[output.html.playground]
copyable = false
copy-js = false
