# yaml-language-server: $schema=../endpoints.schema.json

x-display-name: Application related CDN endpoints
x-description: >
  meow

/applications/{application.id}/app-icons/{hash}.png:
  get:
    x-display-name: ""
    x-description: ""
    x-body: ""
    x-response: ""

/app-icons/{application.id}/{hash}.{PNG||JPEG||WebP||GIF}:
  get:
    x-display-name: ""
    x-description: ""
    x-body: ""
    x-response: ""

/store/applications/{710982414301790216}/assets/{banner_asset.id}.{WebP|PNG}:
  get:
    x-display-name: ""
    x-description: ""
    x-body: ""
    x-response: ""

/app-assets/710982414301790216/store/{banner_asset.id}.{WebP|PNG}:
  get:
    x-display-name: ""
    x-description: ""
    x-body: ""
    x-response: ""
