# yaml-language-server: $schema=../endpoints.schema.json

/users/@me/applications/{application.id}/achievements:
  get:
    x-indicators: []
    x-display-name: Place holder text, wow!
    x-description: Place holder text, wow!
    x-body: null
    x-query: null
    x-response: null
/users/@me/applications/{application.id}/entitlement-ticket:
  post:
    x-indicators: []
    x-display-name: Place holder text, wow!
    x-description: Place holder text, wow!
    x-body: null
    x-query: null
    x-response: null
/users/@me/applications/{application.id}/entitlements:
  get:
    x-indicators: []
    x-display-name: Place holder text, wow!
    x-description: Place holder text, wow!
    x-body: null
    x-query: null
    x-response: null
/users/@me/applications/{entitlement.id}/ticket:
  post:
    x-indicators: []
    x-display-name: Place holder text, wow!
    x-description: Place holder text, wow!
    x-body: null
    x-query: null
    x-response: null
