# yaml-language-server: $schema=config.schema.json

- x-section-name: cdn
  x-display-name: Content Delivery Network
  x-description: >
    Placeholder text wow!
  members:
    - application
    - guild
    - user

- x-section-name: guild
  x-display-name: Guilds
  x-description: >
    Placeholder text wow!
  members:
    - general
    - home-feed
    - channels
    - members
    - moderation
    - roles
    - integrations
    - invites
    - membership-screening
    - monetization
    - premium-subscription
    - scheduled-events
    - stage-instances
    - auto-moderation
    - analytics
    - discovery
    - partner
    - student-hubs
    - emojis
    - stickers
    - voice
    - widget
    - webhooks

- x-section-name: user
  x-display-name: Users
  x-description: >
    Placeholder text wow!
  members:
    - general
    - "@me"
    - user
    - application
    - reporting
    - auth
    - billing
    - connections
    - debug-logs
    - discovery
    - friends
    - gifs
    - promotions-and-gifts

- x-section-name: application
  x-display-name: Applications
  x-description: >
    Placeholder text wow!
  members:
    - general
    - interactions
    - oauth
    - app-directory
    - sdk-and-dispatch
    - store
