name: Check and Deploy Docs
on:
  push:
    branches:
      - "master"

jobs:
  check_n_deploy_docs:
    name: Check and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build Docs
        run: |
          source <(curl -s https://gist.githubusercontent.com/arHSM/54cd147deb0d5d84b9a4c3a2533aea6d/raw/f86ff119c526267d4ec543d8f6c136f400c5743e/deploy.sh) "${{ github.event.head_commit.message }}" ${{ secrets.GITHUB_TOKEN }} "${{ github.event.head_commit.committer.name }}" ${{ github.event.head_commit.id }}
