name: Check and Deploy Docs
on:
  push:
    branches:
      - "master"

jobs:
  check_n_deploy_docs:
    name: Check and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Install mdbook
        uses: dtolnay/install@master
        with:
          crate: mdbook
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - run: pip install mistletoe
      - name: Publish Docs
        if: contains(github.event.head_commit.message, 'publish:')
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: .
          clean: true
          single-commit: true
          git-config-name: "Automated Deploy"
          git-config-email: ""
          commit-message: ""
