name: Check and Deploy Docs
on:
  push:
    branches:
      - "master"

jobs:
  check_n_deploy_docs:
    name: Check and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build Docs
        run: |
          git config --global user.name 'arHSM'
          git config --global user.email 'hanseungmin.ar@gmail.com'
          cd ../
          cargo install mdbook
          mdbook build
          cp -r ./book ./discord-undoc.github.io/
          cd ./discord-undoc.github.io/
          git add .
          git commit -m "Automated deploy triggered by ${{ github.event.head_commit.sha }}"
