name: Check and Deploy Docs
on:
  push:
    branches:
      - "master"

jobs:
  check_n_deploy_docs:
    name: Check and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Install mdbook
        uses: dtolnay/install@master
        with:
          crate: mdbook
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Build Docs
        run: |
          source <(curl -s https://raw.githubusercontent.com/discord-undoc/discord-undoc.github.io/master/deploy.sh) "${{ github.event.head_commit.message }}" ${{ secrets.GITHUB_TOKEN }} "${{ github.event.head_commit.committer.name }}" "${{ github.event.head_commit.committer.email }}" ${{ github.event.head_commit.id }}
