name: Check and Deploy Documentation
on:
  push:
    branches:
      - "master"

jobs:
  check_n_deploy_docs:
    name: Check and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: startsWith(github.event.head_commit.message, 'publish:')
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          architecture: "x64"
        run: pip install pyyaml
      - name: Install mdbook
        if: startsWith(github.event.head_commit.message, 'publish:')
        run: |
          mkdir mdbook

          wget -O "get_mdbook.py" https://gist.githubusercontent.com/arHSM/d077150abcd38aafdd24dfd8bf0eb4aa/raw/add0be08bf75e7931f354941d75d48f0fae6b462/get_mdbook.py
          wget -O "mdbook.tar.gz" $(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/rust-lang/mdBook/releases | python ./get_mdbook.py)
          tar -xzf mdbook.tar.gz

          echo `pwd` >> $GITHUB_PATH
      - name: Deploy GitHub Pages
        if: startsWith(github.event.head_commit.message, 'publish:')
        run: |
          sh ./get_theme.sh

          python ./generate.py
          mdbook build

          git worktree add gh-pages gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          cd gh-pages

          git update-ref -d refs/heads/gh-pages

          rm -rf *
          mv ../book/* .

          git add .
          git commit -m "Automated Deploy triggered by $GITHUB_SHA"
          git push --force
