name: Check and Deploy Docs
on:
  push:
    branches:
      - "master"

jobs:
  check_n_deploy_docs:
    name: Check and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - run: cd ../ && mv ./discord-undoc.github.io ghpages
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: cd ../ && mv ./discord-undoc.github.io master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: mdbook
      - run: |
          git config --global user.name 'arHSM'
          git config --global user.email 'hanseungmin.ar@gmail.com'
          cd master
          mdbook build
          cp -r ./book/* ../ghpages/
          cd ../ghpages/
          git add .
          git commit -m "Automated deploy triggered by ${{ github.event.head_commit.sha }}"
          git push origin gh-pages

